DROP TABLE USERS;
DROP TABLE ACCOUNTS;
CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);
CREATE TABLE ACCOUNTS(
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_TYPE TEXT NOT NULL,
    USER_ID INTEGER NOT NULL,
    BALANCE REAL NOT NULL
);